"""Build the static Dev Edge stock universe from the generated market data.

This prevents the Dev Edge scanner from asking the Render API to calculate all
theme details at page-load time.  The source data is already generated by
fetch_data.py and is published under frontend/public/data/.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "frontend" / "public" / "data"


def load(name: str, default):
    try:
        return json.loads((DATA / name).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default


def main() -> None:
    market = load("market.json", {})
    index = load("stock_index.json", {})
    themes = market.get("themes_5d", {}).get("themes", [])
    theme_pct = {row.get("theme"): row.get("pct") for row in themes if row.get("theme")}
    rows: dict[str, dict] = {}

    for theme in theme_pct:
        detail = market.get(f"theme_detail_{theme}_5d", {})
        for stock in detail.get("stocks", []):
            ticker = str(stock.get("ticker") or "")
            if not ticker:
                continue
            row = rows.setdefault(ticker, {
                "ticker": ticker,
                "name": stock.get("name"),
                "price": stock.get("price"),
                "pct": stock.get("pct"),
                "volume_chg": stock.get("volume_chg"),
                "trade_value": stock.get("trade_value"),
                "market_cap": stock.get("market_cap"),
                "per": stock.get("per"), "pbr": stock.get("pbr"), "peg": stock.get("peg"),
                "themes": [],
            })
            if theme not in row["themes"]:
                row["themes"].append(theme)
            # Keep the first complete value, then supplement sparse static rows.
            for key in ("name", "price", "pct", "volume_chg", "trade_value", "market_cap", "per", "pbr", "peg"):
                if row.get(key) is None and stock.get(key) is not None:
                    row[key] = stock[key]

    for ticker, row in rows.items():
        fallback = index.get(ticker, {})
        row["market_cap"] = row.get("market_cap") or fallback.get("market_cap")
        row["name"] = row.get("name") or fallback.get("name")
        row["price"] = row.get("price") or fallback.get("price")

    # 古いmarket.jsonではテーマ別明細が空のことがある。その場合も、配信済み
    # stock_indexのテーマ・価格・時価総額・騰落率だけで静的スキャンを可能にする。
    # この経路では個別の出来高変化は未取得のためnullのまま明示する。
    detail_rows_available = bool(rows)
    if not rows:
        for ticker, stock in index.items():
            if not stock.get("themes"):
                continue
            rows[ticker] = {
                "ticker": ticker,
                "name": stock.get("name"),
                "price": stock.get("price"),
                "pct": stock.get("pct"),
                "volume_chg": None,
                "trade_value": None,
                "market_cap": stock.get("market_cap"),
                "per": None, "pbr": None, "peg": None,
                "themes": stock.get("themes", []),
            }

    payload = {
        "updated_at": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
        "source": "market.json" if detail_rows_available else "stock_index.json fallback",
        "period": "5d" if detail_rows_available else "stock_index",
        "theme_pct": theme_pct,
        "count": len(rows),
        "data": sorted(rows.values(), key=lambda row: str(row["ticker"])),
    }
    target = DATA / "dev_edge_universe.json"
    target.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
    print(f"generated {target}: {payload['count']} stocks")


if __name__ == "__main__":
    main()
